name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Describe how this feature would be used and who would benefit from it.
      placeholder: |
        This would help when...
        Users could...
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example usage
      description: If applicable, provide an example of how this feature would be used
      render: starlark
    validations:
      required: false

  - type: checkboxes
    id: compatibility
    attributes:
      label: Compatibility considerations
      description: Have you thought about backward compatibility?
      options:
        - label: This feature should be backward compatible
        - label: This feature may require breaking changes
        - label: Not sure about compatibility impact

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or examples about the feature request here.
    validations:
      required: false
